# Exercises

In [1]:
import numpy as np
import math

In [161]:
#Use the following code for the questions below:

a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

1. How many negative numbers are there?

In [162]:
negative= []
for n in a:
    if n < 0:
        negative.append(n)
        total= len(negative)
print("There are a total of", total, "negative numbers.")
    

There are a total of 4 negative numbers.


In [164]:
print(total)

4


2. How many positive numbers are there?

In [68]:
positive= []
for n in a:
    if n > 0:
        positive.append(n)
        total_positives = len(positive)
print("The total number of positive numbers is:", total_positives)

The total number of positive numbers is: 5


In [50]:
print(total_positives)

5


3. How many even positive numbers are there?

In [64]:
even_positive= []
for n in a:
    if n > 0 and n % 2 ==0:
        even_positive.append(n)
        total_ep= len(even_positive)
print("There are", total_ep, "positive even numbers")

There are 3 positive even numbers


In [66]:
print(total_ep)

3


In [67]:
print(even_positive)

[4, 10, 12]


4. If you were to add 3 to each data point, how many positive numbers would there be?

In [58]:
new_array=[]
na_pos= []
for n in a:
    new_array.append(n+3)
for num in new_array:
        if num > 0:
            na_pos.append(num)
            total= len(na_pos)
print("The number of positive numbers after adding three is:", total)


The number of positive numbers after adding three is: 10


In [13]:
print(total)

10


5. If you squared each number, what would the new mean and standard deviation be?

In [83]:
n_array=[]
for n in a:
    n_array.append((np.abs(a))**0.5)
    for num in n_array: 
        m= num.mean()
        st= num.std()
print("The mean is:", m)
print("The standard deviation is:", st)
        
        

The mean is: 1.8886430185340497
The standard deviation is: 1.4490321650016125


In [ ]:
#** double check math

6. A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

In [84]:
N_array= []
for N in n_array:
    N_array.append(N - m)

7. Calculate the z-score for each data point. Recall that the z-score is given by:

Z=x−μ/ σ


In [72]:
z_score_arr=[]
for n in a:
    z_score_arr.append((n-m)/st)

print("The new list with z-scores for each point is:", z_score_arr)

The new list with z-scores for each point is: [1.3950486794086092, 5.359462158478369, 6.680933318168289, 13.949024696462848, -2.5693647996611504, -1.9086292198161905, -1.2478936399712306, -1.2478936399712306, -1.2478936399712306, -5.2123071190409895, 0.7343130995636492, -5.87304269888595]


In [47]:
print(z_score_arr)

[1.3950486794086092, 5.359462158478369, 6.680933318168289, 13.949024696462848, -2.5693647996611504, -1.9086292198161905, -1.2478936399712306, -1.2478936399712306, -1.2478936399712306, -5.2123071190409895, 0.7343130995636492, -5.87304269888595]


In [48]:
print(len(z_score_arr))

12


8. Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.

Awesome Bonus For much more practice with numpy, Go to https://github.com/rougier/numpy-100 and click the "Fork" icon in the upper-right of the screen to fork the repo. This makes a copy of the repo onto your own account. Next, clone your fork https://github.com/your-username/numpy-100 down to your machine. Work through, add, commit, and push your solutions to your own repo.

-------------------------------------------------------------------------

In [119]:
import numpy as np
import math


# Life w/o numpy to life with numpy

## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


# Use python's built in functionality/operators to determine the following:

- Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

- Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

- Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

- Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

- Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

- Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

- Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

- Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

In [100]:
# setup
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [116]:
#sum of a variable
sum_of_a= np.sum(a)

In [120]:
# min_of_a variable
min_of_a= np.min(a)

In [121]:
#max of a variable
max_of_a = np.max(a)

In [123]:
#mean of a
mean_of_a= np.mean(a)

In [124]:
# product_of_a 
product_of_a = np.prod(a)

In [125]:
print(product_of_a)

3628800


In [127]:
#squares_of_a
squares_of_a= np.square(a)

In [147]:
squares_of_a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [138]:
# odds_in_a

odds_in_a= []
for n in a:
    if n % 2 != 0:
        odds_in_a.append(n)

[1]
[1, 3]
[1, 3, 5]
[1, 3, 5, 7]
[1, 3, 5, 7, 9]


In [148]:
evens_in_a= []
for n in a:
    if n % 2 == 0:
        evens_in_a.append(n)

In [149]:
print(evens_in_a)

[2, 4, 6, 8, 10]


## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

In [146]:
b = [[3, 4, 5], [6, 7, 8]]

Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)


In [4]:
b = np.array([[3, 4, 5], 
             [6, 7, 8]])


sum_of_b= b.sum()
print(sum_of_b)

33


Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

In [5]:
min_of_b = b.min()

Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])


In [ ]:
max_of_b = b.max()

Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))


In [174]:
mean_of_b= [(b[0].sum() + b[1].sum()/ (b[0].size + b[1].size))]

In [175]:
print("The mean of be is:", mean_of_b

The mean of be is: [15.5]


Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number

In [176]:
product_of_b= b.prod()

In [177]:
print(product_of_b)

20160


Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)


In [183]:
#Answer:
square_of_b= np.square(b)

In [180]:
print(square_of_b)

[[ 9 16 25]
 [36 49 64]]


In [ ]:
squares_of_b1 = []
for row in b:
    for number in row:
        squares_of_b1.append(number**2)

In [ ]:
print(squares_of_b1)

Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)



In [184]:
odds_in_b= b[b%2==1]

In [186]:
print(odds_in_b)

[3 5 7]


Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)

In [187]:
evens_in_b= b[b%2==0]

In [188]:
print(evens_in_b)

[4 6 8]


Exercise 9 - print out the shape of the array b.


In [200]:
z= np.broadcast(b)

print(z.shape)

(2, 3)


Exercise 10 - transpose the array b.

In [202]:
trans_b= np.transpose(b)

print(trans_b)

[[3 6]
 [4 7]
 [5 8]]


Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

In [204]:
m= np.array(b).reshape(1,6)

print(m)

[[3 4 5 6 7 8]]


Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [205]:
n= np.array(b).reshape(6,1)

print(n)

[[3]
 [4]
 [5]
 [6]
 [7]
 [8]]


## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.

In [274]:
#making it a numpy array
c = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])

Exercise 1 - Find the min, max, sum, and product of c.


In [214]:
min_of_c= c.min()
max_of_c = c.max()
sum_of_c= c.sum()
prod_of_c =c.prod()


print("Min of C:", min_of_c, "Max of C:", max_of_c, "Sum of C:", sum_of_c, "Product of C:", prod_of_c)


Min of C: 1 Max of C: 9 Sum of C: 45 Product of C: 362880


Exercise 2 - Determine the standard deviation of c.

In [215]:
std_of_c= c.std()

print("The standard deviation of C is:", std_of_c)

The standard deviation of C is: 2.581988897471611


Exercise 3 - Determine the variance of c.

In [218]:
var_of_c= c.var()

print("The variance of C is:", var_of_c)

The variance of C is: 6.666666666666667


Exercise 4 - Print out the shape of the array c

In [293]:
shape_c= np.broadcast(c)

print(c.shape)

(3, 3)


Exercise 5 - Transpose c and print out transposed result.


In [225]:
trans_c= np.transpose(c)

print(trans_c)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


Exercise 6 - Get the dot product of the array c with c. 

In [229]:
dt_prd_c= np.dot(c,c)

print(dt_prd_c)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261


In [292]:
trans_c1= np.transpose(c)
mc_c= trans_c1 * c
s_trans_c= mc_c.sum()

print(s_trans_c)

261


In [284]:
# another way to do this:
(c*np.transpose(c)).sum()

261

In [286]:
# another way to do this:
np.sum(c*np.transpose(c))

261

Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

In [261]:
multip_c= c*c

print(multip_c)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [262]:
trans_m_c= np.transpose(multip_c)

print(trans_m_c)

[[ 1 16 49]
 [ 4 25 64]
 [ 9 36 81]]


In [263]:
prd_trans_c= trans_m_c.prod()

print(prd_trans_c)

131681894400


## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

- Exercise 1 - Find the sine of all the numbers in d

- Exercise 2 - Find the cosine of all the numbers in d

- Exercise 3 - Find the tangent of all the numbers in d

- Exercise 4 - Find all the negative numbers in d

- Exercise 5 - Find all the positive numbers in d

- Exercise 6 - Return an array of only the unique numbers in d.

- Exercise 7 - Determine how many unique numbers there are in d.

- Exercise 8 - Print out the shape of d.

- Exercise 9 - Transpose and then print out the shape of d.

- Exercise 10 - Reshape d into an array of 9 x 2




In [294]:
#setup
d = np.array([[90, 30, 45, 0, 120, 180], [45, -90, -30, 270, 90, 0], [60, 45, -45, 90, -45, 180]])

In [270]:
#Find the sine of all the numbers in d
sine_d= np.sin(d)

print(sine_d)

[[ 0.89399666 -0.98803162  0.85090352  0.          0.58061118 -0.80115264]
 [ 0.85090352 -0.89399666  0.98803162 -0.17604595  0.89399666  0.        ]
 [-0.30481062  0.85090352 -0.85090352  0.89399666 -0.85090352 -0.80115264]]


In [271]:
# Find the cosine of all the numbers in d
cosine_d= np.cos(d)

In [272]:
#  Find the tangent of all the numbers in d
tangent_d= np.tan(d)

In [265]:
#Find all the negative numbers in d
neg_in_d= d[d<0]

print(neg_in_d)

[-90 -30 -45 -45]


In [266]:
# Find all the positive numbers in d
pos_in_d= d[d>0]

print(pos_in_d)

[ 90  30  45 120 180  45 270  90  60  45  90 180]


In [279]:
# Determine how many unique numbers there are in d.

uniq_d= np.unique(d)

print(uniq_d)

[-90 -45 -30   0  30  45  60  90 120 180 270]


In [280]:
# Determine how many unique numbers there are in d.
for dd in d:
    count= len(uniq_d)
    
print(count)

11


In [287]:
#  Print out the shape of d.
shape_d= np.broadcast(d)

print(d.shape)

(3, 6)


In [288]:
# Transpose and then print out the shape of d.

trans_d= np.transpose(d)

print(trans_d)

[[ 90  45  60]
 [ 30 -90  45]
 [ 45 -30 -45]
 [  0 270  90]
 [120  90 -45]
 [180   0 180]]


In [291]:
# Reshape d into an array of 9 x 2
A= np.array(d).reshape(9,2)

print(A)

[[ 90  30]
 [ 45   0]
 [120 180]
 [ 45 -90]
 [-30 270]
 [ 90   0]
 [ 60  45]
 [-45  90]
 [-45 180]]
